my_survey/models.py
from otree.api import *
# <standard imports>

import random
# </standard imports>

# Removed Django dependencies for modern oTree

author = 'Yingzhi Liang'

doc = """
Standard Demographic Survey from Veconlab
"""




class Constants(BaseConstants):
    name_in_url = 'my_survey'
    players_per_group = None
    num_rounds = 1
    lottery_safe_A = 2.00
    lottery_safe_B = 1.60
    lottery_risk_A = 3.85
    lottery_risk_B = 0.10



class Subsession(BaseSubsession):

    def creating_session(self):
        #paying_choice = models.IntegerField()
        #die = models.IntegerField()
        paying_choice = random.randint(1,10)
        die = random.randint(1,10)
        self.session.vars['paying_choice'] = paying_choice
        self.session.vars['die'] = die


class Group(BaseGroup):
    pass


class Player(BasePlayer):

    q_instruction1 = models.CharField(initial=None,blank=True,
                                    verbose_name='Which part of the instruction is unclear for you?')
    q_instruction2 = models.CharField(initial=None,blank=True,
                                    verbose_name='What can we do to make it clear?')
    q_instruction3 = models.CharField(initial=None,blank=True,
                                    verbose_name='Any suggestions for this experiment?')
    q_instruction4 = models.CharField(initial=None,blank=True,
                                    verbose_name='Any questions about this experiment?')
    q_country = models.StringField(verbose_name='What is your country of citizenship?')
    q_age = models.PositiveIntegerField(verbose_name='What is your age?',
                                        choices=list(range(13, 125)),
                                        initial=None)
    q_gender = models.CharField(initial=None,
                                choices=['Male', 'Female'],
                                verbose_name='What is your gender?',
                                widget=widgets.RadioSelect())
    q_ethnic = models.CharField(initial=None,
                                verbose_name='Which of the following best describes your racial or ethnic background?',
                                choices=['Asian', 'Black', 'Hispanic', 'Multi-racial', 'Native-American', 'Caucasion'])
    q_marriage = models.CharField(initial=None,verbose_name='What is your marital status?',
                                choices=['Never Married', 'Currently Married', 'Previously Married'])
    q_employ = models.CharField(initial=None,verbose_name='How would you best describe your employment status?',
                                choices=['Employed, Full Time', 'Employed, Part Time', 'Not Employed'])
    q_student = models.CharField(initial=None,verbose_name='What is your student status?',
                                choices=['Full Time', 'Part Time (less than the normal full-course load)', 'Non Student'])
    q_education = models.CharField(initial=None,verbose_name='What is the highest level of study that you have completed?(Use your current year in school if you are a student.)',
                                choices=['College Freshman (first-year)', 'College Sophomore (second-year)', 'College Junior (third-year)',
                                'College Senior (fourth-year)', 'Graduate (first-year)', 'Graduate (second-year)', 'Graduate (third-year)',
                                'Graduate (4+ years)'])
    q_major = models.CharField(initial=None,verbose_name='Which of the following best describes your current major course of study?)',
                                choices=['No Major or Pre-College', 'Arts/Humanities/Education', 'Business/Management (including MBA)',
                                'Economics', 'Politics', 'Psychology', 'Other Social Science', 'Law School (but not pre-law)',
                                'Medical/Nursing (but not pre-med)', 'Math/Science/Engineering/Computer Science', 'Other']
                                )
    q_siblings = models.CharField(initial=None,verbose_name='How many brothers and sisters do you have? (Please do not count yourself.)',
                                choices=['no others', '1 other', '2 others', '3 others', '4 others', '5 others', '6 or more others'])
    q_vote = models.CharField(initial=None,
                              choices=['Yes', 'No'],
                              verbose_name='Have you ever voted in a state or federal government election (in any country)?',
                              widget=widgets.RadioSelect())
    q_job = models.CharField(initial=None,verbose_name='What is the most appropriate description of your primary employment (if any)?',
                               choices=['Not Employed/Student(without outside employment)', 'Agriculture', 'Business/Management', 'Clerical',
                               'Manufacturing', 'Government (non-military)', 'homemaker', 'Military', 'Professional (Law, Medicine, Architecture)',
                               'Research or Research Assistant', 'Teaching or Teaching Assistant', 'Waitperson/Food Service', 'Other'])
    q_income = models.CharField(initial=None,verbose_name='Which category best corresponds to the combined income for all members of your household?(Please guess if you are not sure.)',
                               choices=['Below $10,000', '$10,001 - $20,000', '$20,001 - $30,000', '$30,001 - $40,000',
                               '$40,001 - $50,000', '$50,001 - $60,000', '$60,001 - $70,000', '$70,001 - $80,000',
                               '$80,001 - $90,000', '$90,001 - $100,000', '$100,001 - $120,000', '$120,001 - $140,000',
                               '$140,001 - $160,000', '$160,001 - $180,000', '$180,001 - $200,000', 'above $200,000'])
    q_lottery1 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery2 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery3 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery4 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery5 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery6 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery7 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery8 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery9 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery10 = models.CharField(verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery_instruction1 = models.CharField(initial=None, blank=True, verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery_instruction2 = models.CharField(initial=None, blank=True, verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery_instruction3 = models.CharField(initial=None, blank=True, verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())
    q_lottery_instruction4 = models.CharField(initial=None, blank=True, verbose_name='', choices=['A', 'B'],
                                widget=widgets.RadioSelectHorizontal())

    def choice_list(self):
        choices = [self.q_lottery1, self.q_lottery2, self.q_lottery3, self.q_lottery4, self.q_lottery5, self.q_lottery6, self.q_lottery7, self.q_lottery8, self.q_lottery9, self.q_lottery10]
        return choices

    def set_payoff(self):
        exchange_rate = self.session.config['real_world_currency_per_point']


        if self.choice_list()[self.session.vars['paying_choice'] - 1] == 'A':
        #if self.choice_list()[self.paying_choice - 1] == 'A':
            #if self.die < self.paying_choice + 1:
            if self.session.vars['die'] < self.session.vars['paying_choice'] + 1:
                self.payoff = Constants.lottery_safe_A /exchange_rate
            else:
                self.payoff = Constants.lottery_safe_B /exchange_rate
        else:
            #if self.die < self.paying_choice + 1:
            if self.session.vars['die'] < self.session.vars['paying_choice'] + 1:
                self.payoff = Constants.lottery_risk_A /exchange_rate
            else:
                self.payoff = Constants.lottery_risk_B /exchange_rate

my_survey/views.py
# -*- coding: utf-8 -*-
from __future__ import division

from otree.common import Currency as c, currency_range, safe_json

from . import models
from ._builtin import Page, WaitPage
from .models import Constants

class Introduction(Page):
    form_model = models.Player
    form_fields = ['q_lottery_instruction1',
                    'q_lottery_instruction2',
                    'q_lottery_instruction3',
                    'q_lottery_instruction4']

class Lottery_instruction(Page):
    form_model = models.Player
    form_fields = ['q_lottery_instruction1',
                    'q_lottery_instruction2',
                    'q_lottery_instruction3',
                    'q_lottery_instruction4']


# class Lottery_instruction(Page):
#     form_model = models.Player
#     form_fields = ['q_lottery_instruction1']
    #               'q_lottery_instruction2',
    #               'q_lottery_instruction3',
    #               'q_lottery_instruction4',
    #               ]

class Lottery(Page):
    form_model = models.Player
    form_fields = ['q_lottery1',
                  'q_lottery2',
                  'q_lottery3',
                  'q_lottery4',
                  'q_lottery5',
                  'q_lottery6',
                  'q_lottery7',
                  'q_lottery8',
                  'q_lottery9',
                  'q_lottery10',
                  'q_lottery_instruction1',
                  'q_lottery_instruction2',
                  'q_lottery_instruction3',
                  'q_lottery_instruction4'
                  ]
    def before_next_page(self):
        self.player.set_payoff()



class Results(Page):
    def vars_for_template(self):

        lottery_payoff = self.player.payoff
        payoff_so_far = self.player.participant.payoff
        #decision_for_payment = self.player.paying_choice
        #die_num = self.player.die
        decision_for_payment = self.session.vars['paying_choice']
        die_num = self.session.vars['die']

        return {
            'decision_for_payment': decision_for_payment,
            'die_num': die_num,
            'choice_for_payment': self.player.choice_list()[self.session.vars['paying_choice'] - 1],
            'payment': lottery_payoff.to_real_world_currency(self.session),
            'payoff_so_far': payoff_so_far,
            'payoff_so_far_money': payoff_so_far.to_real_world_currency(self.session)
            }


class Survey(Page):
    form_model = models.Player
    form_fields = ['q_country',
                  'q_age',
                  'q_gender',
                  'q_ethnic',
                  'q_marriage',
                  'q_employ',
                  'q_student',
                  'q_education',
                  'q_major',
                  'q_siblings',
                  'q_vote',
                  'q_job',
                  'q_income',
                  'q_instruction1',
                  'q_instruction2',
                  'q_instruction3',
                  'q_instruction4',]


page_sequence = [
    Introduction,
    Lottery,
    Results,
    Survey
]

# page_sequence = [
#     Lottery_instruction,
#     Lottery,
#     Results
# ]

my_survey/templates/my_survey/Introduction.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Lottery Instructions
{% endblock %}

{% block content %}

    {% include 'my_survey/Lottery_instruction.html' %}

    {% next_button %}

{% endblock %}

my_survey/templates/my_survey/Lottery.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Lottery
{% endblock %}

{% block content %}

    <h4>Please choose between Option A and Option B</h4>
    <table class="table">
        <tr>
            <th>Decision</th>
            <th>Option A</th>
            <th>Option B</th>
            <th>Your Choice</th>
        </tr>

        <tr>
            <td>1st</td>
            <td>$2.00 if the die is 1, $1.60 if the die is 2-10</td>
            <td>$3.85 if the die is 1, $0.10 if the die is 2-10</td>
            <td>{% formfield player.q_lottery1 %}</td>
        </tr>

        <tr>
            <td>2nd</td>
            <td>$2.00 if the die is 1-2, $1.60 if the die is 3-10</td>
            <td>$3.85 if the die is 1-2, $0.10 if the die is 3-10</td>
            <td>{% formfield player.q_lottery2 %}</td>
        </tr>

        <tr>
            <td>3rd</td>
            <td>$2.00 if the die is 1-3, $1.60 if the die is 4-10</td>
            <td>$3.85 if the die is 1-3, $0.10 if the die is 4-10</td>
            <td>{% formfield player.q_lottery3 %}</td>
        </tr>

        <tr>
            <td>4th</td>
            <td>$2.00 if the die is 1-4, $1.60 if the die is 5-10</td>
            <td>$3.85 if the die is 1-4, $0.10 if the die is 5-10</td>
            <td>{% formfield player.q_lottery4 %}</td>
        </tr>

        <tr>
            <td>5th</td>
            <td>$2.00 if the die is 1-5, $1.60 if the die is 6-10</td>
            <td>$3.85 if the die is 1-5, $0.10 if the die is 6-10</td>
            <td>{% formfield player.q_lottery5 %}</td>
        </tr>

        <tr>
            <td>6th</td>
            <td>$2.00 if the die is 1-6, $1.60 if the die is 7-10</td>
            <td>$3.85 if the die is 1-6, $0.10 if the die is 7-10</td>
            <td>{% formfield player.q_lottery6 %}</td>
        </tr>

        <tr>
            <td>7th</td>
            <td>$2.00 if the die is 1-7, $1.60 if the die is 8-10</td>
            <td>$3.85 if the die is 1-7, $0.10 if the die is 8-10</td>
            <td>{% formfield player.q_lottery7 %}</td>
        </tr>

        <tr>
            <td>8th</td>
            <td>$2.00 if the die is 1-8, $1.60 if the die is 9-10</td>
            <td>$3.85 if the die is 1-8, $0.10 if the die is 9-10</td>
            <td>{% formfield player.q_lottery8 %}</td>
        </tr>

        <tr>
            <td>9th</td>
            <td>$2.00 if the die is 1-9, $1.60 if the die is 10</td>
            <td>$3.85 if the die is 1-9, $0.10 if the die is 10</td>
            <td>{% formfield player.q_lottery9 %}</td>
        </tr>

        <tr>
            <td>10th</td>
            <td>$2.00 if the die is 1-10</td>
            <td>$3.85 if the die is 1-10</td>
            <td>{% formfield player.q_lottery10 %}</td>
        </tr>
    </table>
    <p></p>

    {% next_button %}
    {% include 'my_survey/Lottery_instruction.html' %}


{% endblock %}

my_survey/templates/my_survey/Lottery_instruction.html
{% load staticfiles otree_tags %}

<div class="instructions well well-lg">

    <h3 class="panel-sub-heading">
        Lottery Instructions
    </h3>

    <p>
      You will be making choices between two lotteries, such as those represented as "Option A" and "Option B" below.
      The money prizes are determined by the computer equivalent of throwing a ten-sided die.
      Each outcome, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, is equally likely. If you choose Option A in the row shown below,
      you will have a 1 in 10 chance of earning $2.00 and a 9 in 10 chance of earning $1.60. Similarly,
      Option B offers a 1 in 10 chance of earning $3.85 and a 9 in 10 chance of earning $0.10.
    </p>

    <table class="table">
        <tr>
            <th>Decision</th>
            <th>Option A</th>
            <th>Option B</th>
            <th>Your Choice</th>
        </tr>

        <tr>
            <td>1st</td>
            <td>$2.00 if the die is 1, $1.60 if the die is 2-10</td>
            <td>$3.85 if the die is 1, $0.10 if the die is 2-10</td>
            <td>{% formfield player.q_lottery_instruction1 %}</td>
        </tr>
    </table>
    <p></p>
    <ul>
      <li>Each row of the decision table contains a pair of choices between Option A and Option B.
      <li>You make your choice by clicking on the "A" or "B" buttons on the right. Only one option in each row can be selected, and you may change your decision as you wish.
      <li>Note, try clicking on one of the radio buttons, then change by clicking on the other one.
    </ul>

    <p>
      Even though you will make ten decisions, only one of these will end up being used.
      The selection of the one to be used depends on the "throw of the die" that is the determined by the computer's random number generator.
      No decision is any more likely to be used than any other, and you will not know in advance which one will be selected,
      so please think about each one carefully. This random selection of a decision fixes the row (i.e. the Decision) that will be used.
    </p>
    <p>
      For example, suppose that you make all ten decisions and the throw of the die is 9,
      then your choice, A or B, for decision 9 below would be used and the other decisions would not be used.
    </p>
    <table class="table">
        <tr>
            <th>Decision</th>
            <th>Option A</th>
            <th>Option B</th>
            <th>Your Choice</th>
        </tr>

        <tr>
            <td>9th</td>
            <td>$2.00 if the die is 1-9, $1.60 if the die is 10</td>
            <td>$3.85 if the die is 1-9, $0.10 if the die is 10</td>
            <td>{% formfield player.q_lottery_instruction2 %}</td>

        </tr>
    </table>
    <p></p>

    <p>
      After the random die throw fixes the Decision row that will be used,
      we need to obtain a second random number that determines the earnings for the Option you chose for that row.
      In Decision 9 below, for example, a throw of 1, 2, 3, 4, 5, 6, 7, 8, or 9 will result in the higher payoff for the option you chose,
      and a throw of 10 will result in the lower payoff.
    </p>

    <table class="table">
        <tr>
            <th>Decision</th>
            <th>Option A</th>
            <th>Option B</th>
            <th>Your Choice</th>
        </tr>

        <tr>
            <td>9th</td>
            <td>$2.00 if the die is 1-9, $1.60 if the die is 10</td>
            <td>$3.85 if the die is 1-9, $0.10 if the die is 10</td>
            <td>{% formfield player.q_lottery_instruction3 %}</td>

        </tr>

        <tr>
            <td>10th</td>
            <td>$2.00 if the die is 1-10</td>
            <td>$3.85 if the die is 1-10</td>
            <td>{% formfield player.q_lottery_instruction4 %}</td>

        </tr>
    </table>
    <p></p>
    <p>
      For decision 10, the random die throw will not be needed, since the choice is between
      amounts of money that are fixed: $2.00 for Option A and $3.85 for Option B.
    </p>

    <ul>
      <li><strong>Making Ten Decisions:</strong> After you finish these instructions, you will see a table with 10 decisions in 10 separate rows,
        and you choose by clicking on the buttons on the right, option A or option B, for each of the 10 rows.
        You may make these choices in any order and change them as much as you wish until you press the Submit button at the bottom.
      <li><strong>The Relevant Decision:</strong> One of the rows is then selected at random, and the Option (A or B) that you chose in that row will be used to determine your earnings.
        Note: Please think about each decision carefully, since each row is equally likely to end up being the one that is used to determine payoffs.
      <li><strong>Determining the Payoff:</strong> After one of the decisions has been randomly selected,
        the computer will generate another random number that corresponds to the throw of a ten sided die.
        The number is equally likely to be 1, 2, 3, ... 10. This random number determines your earnings for the Option (A or B) that you previously selected for the decision being used.
    </ul>

    <h4>Instructions Summary</h4>
    <ul>
      <li>To summarize, you will indicate an option, A or B, for each of the rows by clicking on the "radio buttons" on the right side of the table.
      <li>Then a random number fixes which row of the table (i.e. which decision) is relevant for your earnings.
      <li>In that row, your decision fixed the choice for that row, Option A or Option B,
        and a final random number will determine the money payoff for the decision you made.
      <li>Payoffs will be made in cash.
    </ul>

    <p>
        For your convenience, these instructions will remain available to you on all subsequent screens of this study.
    </p>

</div>

my_survey/templates/my_survey/Results.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Lottery Result
{% endblock %}

{% block content %}
<p>
  Recall that you must make decisions for all choices that you face
  before one of the decisions will be selected at random to determine your earnings.
</p>

<p>
  After you have made all decisions and one of these has been selected to be used,
  the program will generate a random number to calculate your earnings for the decision problem that turns out to be relevant.
  Now we will generate the random number that determines the throw of the 10-sided die
  in such a manner that each outcome, 1, 2, 3, 4, 5, 6, 7, 8, 9, or 10 is equally likely.
</p>
<p>
  Your choice list is {{player.choice_list}}.
</p>

<div style="font-size: 1.2em; font-weight: bold;">
  <p>
    The decision chosen for payment is <span style="color: red;">{{decision_for_payment}}</span>. The corresponding choice is <span style="color: red;">{{choice_for_payment}}</span>.
    The random number that determines the throw of the 10-sided die is <span style="color: red;">{{die_num}}</span>.
    You earned <span style="color: red;">{{payment}}</span> from the lottery game.
  </p>
  <p>
    In total, you earned <span style="color: red;">{{payoff_so_far_money}}</span> from the review questions, the investment game and the lottery game.
  </p>
</div>

<p>
<!--
Documentation on how to write a django template here:
https://docs.djangoproject.com/en/dev/topics/templates/

Bootstrap comes pre-loaded, so you can use any Bootstrap elements:
http://getbootstrap.com/components/

-->

    {% next_button %}
{% endblock %}

my_survey/templates/my_survey/Survey.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}

{% block title %}
    Survey
{% endblock %}

{% block content %}

    <p>
        Please answer the following questions. 
    </p>

    {% formfield player.q_country %}
    {% formfield player.q_age %}
    {% formfield player.q_gender %}
    {% formfield player.q_ethnic %}
    {% formfield player.q_marriage %}
    {% formfield player.q_employ %}
    {% formfield player.q_student %}
    {% formfield player.q_education %}
    {% formfield player.q_major %}
    {% formfield player.q_siblings %}
    {% formfield player.q_vote %}
    {% formfield player.q_job %}
    {% formfield player.q_income %}

    <hr>
    <p><em>The following questions are optional:</em></p>
    {% formfield player.q_instruction1 %}
    {% formfield player.q_instruction2 %}
    {% formfield player.q_instruction3 %}
    {% formfield player.q_instruction4 %}

    {% next_button %}
    
{% endblock %}

{% block content_at_bottom_of_body %}

    <script type="text/javascript">
        function sort(a, b) {
            return (a.innerHTML > b.innerHTML) ? 1 : -1;
        }
        $('#id_q_country option').sort(sort).appendTo('#id_q_country');
    </script>

{% endblock %}